// spec-to-gsap.js — converts pipeline spec → GSAP timeline module
'use strict';

// GSAP easing approximations for spring types
const GSAP_EASE = {
  ease_in_out:      'power2.inOut',
  ease_out:         'power2.out',
  ease_in:          'power2.in',
  linear:           'none',
  spring_bounce:    'back.out(1.7)',    // underdamped spring approximation
  spring_overshoot: 'back.out(2.5)',   // stronger overshoot
};

// Spec property → GSAP property
const PROP_MAP = {
  translateX:   'x',
  translateY:   'y',
  translateZ:   'z',
  rotateX:      'rotationX',
  rotateY:      'rotationY',
  rotateZ:      'rotationZ',
  scale:        'scale',
  scaleX:       'scaleX',
  scaleY:       'scaleY',
  opacity:      'opacity',
  width:        'width',
  height:       'height',
  borderRadius: 'borderRadius',
};

function frameToSec(frame, fps) {
  return +(frame / fps).toFixed(3);
}

function layerDuration(layer, spec) {
  if (layer.frame_range) {
    return frameToSec(layer.frame_range[1] - layer.frame_range[0], spec.fps);
  }
  if (layer.phase && spec.phases) {
    const phase = spec.phases.find(p => p.id === layer.phase);
    if (phase) return +(phase.end - phase.start).toFixed(3);
  }
  return spec.duration;
}

function layerPosition(layer, spec) {
  if (layer.start_at != null) return layer.start_at;
  if (layer.frame_range) return frameToSec(layer.frame_range[0], spec.fps);
  if (layer.phase && spec.phases) {
    const phase = spec.phases.find(p => p.id === layer.phase);
    if (phase) return phase.start;
  }
  return 0;
}

function toCamel(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function toPascal(name) {
  return name.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('');
}

function buildTween(layer, spec) {
  const prop    = PROP_MAP[layer.property] || layer.property;
  const ease    = GSAP_EASE[layer.easing] || 'power2.out';
  const dur     = layerDuration(layer, spec);
  const pos     = layerPosition(layer, spec);
  const selector = `.${toCamel(layer.id)}`;

  if (layer.keyframes) {
    // Keyframe path → GSAP motionPath / keyframes object
    const kfObj = layer.keyframes.map((v, i) => ({
      [prop]: v,
      ease,
    }));
    return `  tl.to('${selector}', { keyframes: ${JSON.stringify(kfObj)}, duration: ${dur} }, ${pos});`;
  }

  const fromVal = layer.from != null ? layer.from : undefined;
  const toVal   = layer.to   != null ? layer.to   : undefined;

  if (fromVal != null) {
    return `  tl.from('${selector}', { ${prop}: ${fromVal}, duration: ${dur}, ease: '${ease}' }, ${pos});`;
  }
  return `  tl.to('${selector}', { ${prop}: ${toVal}, duration: ${dur}, ease: '${ease}' }, ${pos});`;
}

function specToGsap(spec) {
  const fnName = `create${toPascal(spec.name)}`;
  const layers = (spec.layers || []).filter(l => l.render_compatible !== false);

  // Unique selectors for HTML scaffold comment
  const ids = [...new Set(layers.map(l => l.id))];
  const selectorList = ids.map(id => `    <div class="${toCamel(id)}"></div>`).join('\n');

  const tweens = layers.map(l => buildTween(l, spec)).join('\n');

  return `/**
 * ${spec.name} — GSAP animation
 * Generated by the animate pipeline. Edit freely.
 *
 * Duration: ${spec.duration}s  FPS: ${spec.fps}
 * NOTE: Spring easing is approximated with GSAP back/elastic eases.
 *       For true spring physics use React Spring or Motion instead.
 *
 * Expected HTML structure:
 * <div class="animation-root">
${selectorList}
 * </div>
 */

import { gsap } from 'gsap';

/**
 * @param {Element} container — the .animation-root element
 * @returns {gsap.core.Timeline}
 */
export function ${fnName}(container) {
  const tl = gsap.timeline({ paused: true });

${tweens}

  return tl;
}

// Autoplay when imported as a demo
if (typeof document !== 'undefined') {
  document.addEventListener('DOMContentLoaded', () => {
    const root = document.querySelector('.animation-root');
    if (root) ${fnName}(root).play();
  });
}
`;
}

module.exports = { specToGsap };
