// .claude/skills/animate/spec-to-ae.js
'use strict';

// AE temporal ease influence values per easing type
const AE_EASE = {
  spring_overshoot: { outInfluence: 40, inInfluence: 20 },
  bounce:           { outInfluence: 40, inInfluence: 20 },
  ease_in_out:      { outInfluence: 33, inInfluence: 33 },
  ease_in:          { outInfluence: 60, inInfluence: 10 },
  ease_out:         { outInfluence: 10, inInfluence: 60 },
  linear:           { outInfluence: 0,  inInfluence: 0  },
};

// AE transform property names inside "ADBE Transform Group"
const AE_PROP = {
  translateX: 'Position', translateY: 'Position',
  translateZ: 'Position',
  scale: 'Scale', scaleX: 'Scale', scaleY: 'Scale',
  opacity: 'Opacity',
  rotate: 'Rotation', rotateX: 'X Rotation',
  rotateY: 'Y Rotation', rotateZ: 'Z Rotation',
};

function layerScript(layer, index, spec) {
  const totalFrames = Math.round(spec.duration * spec.fps);
  const startFrame  = Math.round((layer.start_at || 0) * spec.fps);
  const ease = AE_EASE[layer.easing] || AE_EASE.ease_in_out;
  const prop = AE_PROP[layer.property] || 'Position';
  const assetNote = spec.assets?.[layer.id]
    ? `// asset: ${spec.assets[layer.id]} — copy to project, link manually`
    : '// no asset — using placeholder solid';

  const isOpacity = layer.property === 'opacity';
  const mult = isOpacity ? 100 : 1;

  const keyframeLines = layer.to_final !== undefined
    ? `  prop${index}.setValueAtTime(${startFrame} / comp.frameRate, ${layer.from * mult});
  prop${index}.setValueAtTime(${Math.round(totalFrames * 0.6)} / comp.frameRate, ${layer.to * mult});
  prop${index}.setValueAtTime(${totalFrames} / comp.frameRate, ${layer.to_final * mult});`
    : `  prop${index}.setValueAtTime(${startFrame} / comp.frameRate, ${layer.from * mult});
  prop${index}.setValueAtTime(${totalFrames} / comp.frameRate, ${layer.to * mult});`;

  return `
  // --- Layer ${index}: ${layer.id} (${layer.property}) ---
  ${assetNote}
  var layer${index} = comp.layers.addSolid([0.18, 0.18, 0.18], "${layer.id}", comp.width, comp.height, 1.0);
  layer${index}.name = "${layer.id}";
  var tg${index} = layer${index}.property("ADBE Transform Group");
  var prop${index} = tg${index}.property("${prop}");
${keyframeLines}
  if (prop${index}.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, ${ease.outInfluence});
    var easeIn  = new KeyframeEase(0, ${ease.inInfluence});
    prop${index}.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop${index}.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
  }`;
}

function specToAeScript(spec) {
  const layerBlocks = spec.layers
    .map((layer, i) => layerScript(layer, i, spec))
    .join('\n');

  return `// Generated by animate-pipeline — ${spec.name}
// Run in After Effects: File > Scripts > Run Script File

(function() {
  var comp = app.project.items.addComp(
    "${spec.name}",
    1294, 720, 1,
    ${spec.duration}, ${spec.fps}
  );
${layerBlocks}

  comp.openInViewer();
  alert("Created: ${spec.name}\\nLayers: ${spec.layers.length}\\nDuration: ${spec.duration}s @ ${spec.fps}fps");
})();
`;
}

module.exports = { specToAeScript };
