// .claude/skills/animate/spec-to-css.js
'use strict';

const CSS_EASING = {
  spring_overshoot: 'cubic-bezier(0.2, 1.3, 0.4, 1)',
  bounce:           'cubic-bezier(0.2, 1.5, 0.4, 1)',
  ease_in_out:      'cubic-bezier(0.4, 0, 0.2, 1)',
  ease_in:          'cubic-bezier(0.4, 0, 1.0, 1)',
  ease_out:         'cubic-bezier(0.0, 0, 0.2, 1)',
  linear:           'linear',
};

function propValue(property, value) {
  if (property === 'opacity')                 return `opacity: ${value}`;
  if (property === 'scale')                   return `transform: scale(${value})`;
  if (property === 'scaleX')                  return `transform: scaleX(${value})`;
  if (property === 'scaleY')                  return `transform: scaleY(${value})`;
  if (property === 'translateX')              return `transform: translateX(${value}px)`;
  if (property === 'translateY')              return `transform: translateY(${value}px)`;
  if (property === 'translateZ')              return `transform: translateZ(${value}px)`;
  if (property.startsWith('rotate'))          return `transform: ${property}(${value}deg)`;
  return `transform: ${property}(${value})`;
}

function specToCss(spec) {
  const has3d = spec['3d'] && (spec['3d'].type === 'css3d' || spec.layers.some(l =>
    l.property === 'translateZ' || l.property === 'rotateX' || l.property === 'rotateY'
  ));
  const perspective = (spec['3d'] && spec['3d'].perspective) || 900;

  // Build @keyframes blocks (one per layer)
  const keyframeBlocks = spec.layers.map(layer => {
    const animName = `${spec.name}-${layer.id}-${layer.property}`;
    const easing = CSS_EASING[layer.easing] || 'ease';

    if (layer.to_final !== undefined) {
      return `@keyframes ${animName} {
  0%   { ${propValue(layer.property, layer.from)}; }
  60%  { ${propValue(layer.property, layer.to)}; }
  100% { ${propValue(layer.property, layer.to_final)}; }
}`;
    }
    return `@keyframes ${animName} {
  from { ${propValue(layer.property, layer.from)}; }
  to   { ${propValue(layer.property, layer.to)}; }
}`;
  });

  // Group layers by id → one class rule with comma-separated animations
  const byId = {};
  for (const layer of spec.layers) {
    if (!byId[layer.id]) byId[layer.id] = [];
    byId[layer.id].push(layer);
  }

  const classRules = Object.entries(byId).map(([id, layers]) => {
    const animations = layers.map(layer => {
      const animName = `${spec.name}-${layer.id}-${layer.property}`;
      const easing = CSS_EASING[layer.easing] || 'ease';
      const delay = layer.start_at ? `${layer.start_at}s` : '0s';
      return `${animName} ${spec.duration}s ${easing} ${delay} both`;
    });
    return `.${spec.name}-${id} {\n  animation: ${animations.join(',\n             ')};\n}`;
  });

  // 3D root wrapper — only emitted when spec uses 3D transforms
  const rootRule = has3d
    ? `.${spec.name} {\n  perspective: ${perspective}px;\n  perspective-origin: 50% 50%;\n}\n\n.${spec.name} > * {\n  transform-style: preserve-3d;\n}`
    : null;

  const allBlocks = [
    ...(rootRule ? [rootRule] : []),
    ...keyframeBlocks,
    ...classRules,
  ];
  return `/* Generated by animate-pipeline: ${spec.name} */\n\n${allBlocks.join('\n\n')}`;
}

module.exports = { specToCss };
