// .claude/skills/animate/spec-to-css.js
'use strict';

const CSS_EASING = {
  spring_overshoot: 'cubic-bezier(0.2, 1.3, 0.4, 0)',
  bounce:           'cubic-bezier(0.2, 1.5, 0.4, 0)',
  ease_in_out:      'cubic-bezier(0.4, 0, 0.2, 1)',
  ease_in:          'cubic-bezier(0.4, 0, 1.0, 1)',
  ease_out:         'cubic-bezier(0.0, 0, 0.2, 1)',
  linear:           'linear',
};

function propValue(property, value) {
  if (property === 'opacity')                 return `opacity: ${value}`;
  if (property === 'scale')                   return `transform: scale(${value})`;
  if (property === 'scaleX')                  return `transform: scaleX(${value})`;
  if (property === 'scaleY')                  return `transform: scaleY(${value})`;
  if (property === 'translateX')              return `transform: translateX(${value}px)`;
  if (property === 'translateY')              return `transform: translateY(${value}px)`;
  if (property.startsWith('rotate'))          return `transform: ${property}(${value}deg)`;
  return `transform: ${property}(${value})`;
}

function specToCss(spec) {
  const blocks = spec.layers.map(layer => {
    const animName = `${spec.name}-${layer.id}-${layer.property}`;
    const className = `.${spec.name}-${layer.id}`;
    const easing = CSS_EASING[layer.easing] || 'ease';
    const delay = layer.start_at ? `${layer.start_at}s` : '0s';

    let keyframes;
    if (layer.to_final !== undefined) {
      keyframes = `@keyframes ${animName} {
  0%   { ${propValue(layer.property, layer.from)}; }
  60%  { ${propValue(layer.property, layer.to)}; }
  100% { ${propValue(layer.property, layer.to_final)}; }
}`;
    } else {
      keyframes = `@keyframes ${animName} {
  from { ${propValue(layer.property, layer.from)}; }
  to   { ${propValue(layer.property, layer.to)}; }
}`;
    }

    const rule = `${className} {
  animation: ${animName} ${spec.duration}s ${easing} ${delay} both;
}`;

    return `${keyframes}\n\n${rule}`;
  });

  return `/* Generated by animate-pipeline: ${spec.name} */\n\n${blocks.join('\n\n')}`;
}

module.exports = { specToCss };
