// .claude/skills/animate/spec-to-ae.js
'use strict';

// AE temporal ease influence values per easing type
const AE_EASE = {
  spring_overshoot: { outInfluence: 40, inInfluence: 20 },
  bounce:           { outInfluence: 40, inInfluence: 20 },
  ease_in_out:      { outInfluence: 33, inInfluence: 33 },
  ease_in:          { outInfluence: 60, inInfluence: 10 },
  ease_out:         { outInfluence: 10, inInfluence: 60 },
};

// AE transform property names inside "ADBE Transform Group"
const AE_PROP = {
  translateX: 'Position', translateY: 'Position',
  translateZ: 'Position',
  scale: 'Scale', scaleX: 'Scale', scaleY: 'Scale',
  opacity: 'Opacity',
  rotate: 'Rotation', rotateX: 'X Rotation',
  rotateY: 'Y Rotation', rotateZ: 'Z Rotation',
};

function layerScript(layer, index, spec) {
  const totalFrames = Math.round(spec.duration * spec.fps);
  const startFrame  = Math.round((layer.start_at || 0) * spec.fps);
  const ease = AE_EASE[layer.easing] || AE_EASE.ease_in_out;
  const prop = AE_PROP[layer.property] || 'Position';
  const assetNote = spec.assets?.[layer.id]
    ? `// asset: ${spec.assets[layer.id]} — copy to project, link manually`
    : '// no asset — using placeholder solid';

  const isOpacity = layer.property === 'opacity';
  const isPosition = layer.property.startsWith('translate');
  const is3d = layer.property === 'translateZ' || layer.property === 'rotateX' || layer.property === 'rotateY';
  const mult = isOpacity ? 100 : 1;

  // AE position is always [x, y] for 2D or [x, y, z] for 3D layers
  function posValue(v) {
    if (layer.property === 'translateX') return is3d ? `[${v}, 0, 0]` : `[${v}, 0]`;
    if (layer.property === 'translateY') return is3d ? `[0, ${v}, 0]` : `[0, ${v}]`;
    if (layer.property === 'translateZ') return `[0, 0, ${v}]`; // Z only meaningful in 3D mode
    return is3d ? `[${v}, ${v}, 0]` : `[${v}, ${v}]`;
  }

  function formatValue(v) {
    return isPosition ? posValue(v * mult) : v * mult;
  }

  const enable3d = is3d ? `  layer${index}.threeDLayer = true;\n` : '';

  const keyframeLines = layer.to_final !== undefined
    ? `  prop${index}.setValueAtTime(${startFrame} / comp.frameRate, ${formatValue(layer.from)});
  prop${index}.setValueAtTime(${Math.round(totalFrames * 0.6)} / comp.frameRate, ${formatValue(layer.to)});
  prop${index}.setValueAtTime(${totalFrames} / comp.frameRate, ${formatValue(layer.to_final)});`
    : `  prop${index}.setValueAtTime(${startFrame} / comp.frameRate, ${formatValue(layer.from)});
  prop${index}.setValueAtTime(${totalFrames} / comp.frameRate, ${formatValue(layer.to)});`;

  return `
  // --- Layer ${index}: ${layer.id} (${layer.property}) ---
  ${assetNote}
  var layer${index} = comp.layers.addSolid([0.18, 0.18, 0.18], "${layer.id}", comp.width, comp.height, 1.0);
  layer${index}.name = "${layer.id}";
${enable3d}  var tg${index} = layer${index}.property("ADBE Transform Group");
  var prop${index} = tg${index}.property("${prop}");
${keyframeLines}
  ${layer.easing === 'linear' ? `
  // Linear: set interpolation type instead of ease handles (KeyframeEase(0,0) is invalid in AE)
  for (var ki = 1; ki <= prop${index}.numKeys; ki++) {
    prop${index}.setInterpolationTypeAtKey(ki, KeyframeInterpolationType.LINEAR);
  }` : `
  if (prop${index}.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, ${ease.outInfluence});
    var easeIn  = new KeyframeEase(0, ${ease.inInfluence});
    prop${index}.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop${index}.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop${index}.numKeys >= 3) {
      prop${index}.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }`}`;
}

function specToAeScript(spec) {
  const layerBlocks = spec.layers
    .map((layer, i) => layerScript(layer, i, spec))
    .join('\n');

  // Optional camera block — added when spec has camera or 3D layers
  const has3dLayers = spec.layers.some(l =>
    l.property === 'translateZ' || l.property === 'rotateX' || l.property === 'rotateY'
  );
  const camConfig = spec.camera || {};
  const camPos = camConfig.position || [0, 0, -500];
  const cameraBlock = (has3dLayers || spec['3d']) ? `
  // ─── Camera (required for 3D layers) ─────────────────────
  var camera = comp.layers.addCamera("Camera 1", [comp.width / 2, comp.height / 2]);
  camera.property("ADBE Transform Group").property("Position").setValue([${camPos[0] + 'comp.width/2'}, ${camPos[1] + 'comp.height/2'}, ${camPos[2] || -500}]);
` : '';

  return `// Generated by animate-pipeline — ${spec.name}
// Run in After Effects: File > Scripts > Run Script File

(function() {
  var comp = app.project.items.addComp(
    "${spec.name}",
    ${spec.width || 1294}, ${spec.height || 720}, 1,
    ${spec.duration}, ${spec.fps}
  );
${cameraBlock}${layerBlocks}

  comp.openInViewer();
  alert("Created: ${spec.name}\\nLayers: ${spec.layers.length}\\nDuration: ${spec.duration}s @ ${spec.fps}fps");
})();
`;
}

module.exports = { specToAeScript };
