// Generated by animate-pipeline — cards
// Run in After Effects: File > Scripts > Run Script File

(function() {
  var comp = app.project.items.addComp(
    "cards",
    1294, 720, 1,
    6, 30
  );

  // --- Layer 0: card (translateY) ---
  // no asset — using placeholder solid
  var layer0 = comp.layers.addSolid([0.18, 0.18, 0.18], "card", comp.width, comp.height, 1.0);
  layer0.name = "card";
  var tg0 = layer0.property("ADBE Transform Group");
  var prop0 = tg0.property("Position");
  prop0.setValueAtTime(0 / comp.frameRate, [0, NaN]);
  prop0.setValueAtTime(180 / comp.frameRate, [0, NaN]);
  
  if (prop0.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 33);
    var easeIn  = new KeyframeEase(0, 33);
    prop0.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop0.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop0.numKeys >= 3) {
      prop0.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 1: card (rotateX) ---
  // no asset — using placeholder solid
  var layer1 = comp.layers.addSolid([0.18, 0.18, 0.18], "card", comp.width, comp.height, 1.0);
  layer1.name = "card";
  var tg1 = layer1.property("ADBE Transform Group");
  var prop1 = tg1.property("X Rotation");
  prop1.setValueAtTime(0 / comp.frameRate, NaN);
  prop1.setValueAtTime(180 / comp.frameRate, NaN);
  
  if (prop1.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 33);
    var easeIn  = new KeyframeEase(0, 33);
    prop1.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop1.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop1.numKeys >= 3) {
      prop1.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 2: card (rotateZ) ---
  // no asset — using placeholder solid
  var layer2 = comp.layers.addSolid([0.18, 0.18, 0.18], "card", comp.width, comp.height, 1.0);
  layer2.name = "card";
  var tg2 = layer2.property("ADBE Transform Group");
  var prop2 = tg2.property("Z Rotation");
  prop2.setValueAtTime(0 / comp.frameRate, NaN);
  prop2.setValueAtTime(180 / comp.frameRate, NaN);
  
  if (prop2.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop2.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop2.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop2.numKeys >= 3) {
      prop2.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 3: card (scale) ---
  // no asset — using placeholder solid
  var layer3 = comp.layers.addSolid([0.18, 0.18, 0.18], "card", comp.width, comp.height, 1.0);
  layer3.name = "card";
  var tg3 = layer3.property("ADBE Transform Group");
  var prop3 = tg3.property("Scale");
  prop3.setValueAtTime(0 / comp.frameRate, NaN);
  prop3.setValueAtTime(180 / comp.frameRate, NaN);
  
  if (prop3.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 33);
    var easeIn  = new KeyframeEase(0, 33);
    prop3.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop3.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop3.numKeys >= 3) {
      prop3.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 4: card (opacity) ---
  // no asset — using placeholder solid
  var layer4 = comp.layers.addSolid([0.18, 0.18, 0.18], "card", comp.width, comp.height, 1.0);
  layer4.name = "card";
  var tg4 = layer4.property("ADBE Transform Group");
  var prop4 = tg4.property("Opacity");
  prop4.setValueAtTime(0 / comp.frameRate, NaN);
  prop4.setValueAtTime(180 / comp.frameRate, NaN);
  
  if (prop4.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop4.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop4.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop4.numKeys >= 3) {
      prop4.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  comp.openInViewer();
  alert("Created: cards\nLayers: 5\nDuration: 6s @ 30fps");
})();
