// Generated by animate-pipeline — card-spring-enter
// Run in After Effects: File > Scripts > Run Script File

(function() {
  var comp = app.project.items.addComp(
    "card-spring-enter",
    1294, 720, 1,
    1.2, 30
  );

  // --- Layer 0: card (translateY) ---
  // asset: card.png — copy to project, link manually
  var layer0 = comp.layers.addSolid([0.18, 0.18, 0.18], "card", comp.width, comp.height, 1.0);
  layer0.name = "card";
  var tg0 = layer0.property("ADBE Transform Group");
  var prop0 = tg0.property("Position");
  prop0.setValueAtTime(0 / comp.frameRate, [0, 120]);
  prop0.setValueAtTime(36 / comp.frameRate, [0, 0]);
  if (prop0.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop0.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop0.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop0.numKeys >= 3) {
      prop0.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 1: card (opacity) ---
  // asset: card.png — copy to project, link manually
  var layer1 = comp.layers.addSolid([0.18, 0.18, 0.18], "card", comp.width, comp.height, 1.0);
  layer1.name = "card";
  var tg1 = layer1.property("ADBE Transform Group");
  var prop1 = tg1.property("Opacity");
  prop1.setValueAtTime(0 / comp.frameRate, 0);
  prop1.setValueAtTime(36 / comp.frameRate, 100);
  if (prop1.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop1.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop1.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop1.numKeys >= 3) {
      prop1.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  comp.openInViewer();
  alert("Created: card-spring-enter\nLayers: 2\nDuration: 1.2s @ 30fps");
})();
