// Generated by animate-pipeline — logo-reveal
// Run in After Effects: File > Scripts > Run Script File

(function() {
  var comp = app.project.items.addComp(
    "logo-reveal",
    1294, 720, 1,
    0.8, 30
  );

  // --- Layer 0: logo (scale) ---
  // no asset — using placeholder solid
  var layer0 = comp.layers.addSolid([0.18, 0.18, 0.18], "logo", comp.width, comp.height, 1.0);
  layer0.name = "logo";
  var tg0 = layer0.property("ADBE Transform Group");
  var prop0 = tg0.property("Scale");
  prop0.setValueAtTime(0 / comp.frameRate, 80);
  prop0.setValueAtTime(24 / comp.frameRate, 100);
  
  if (prop0.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop0.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop0.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop0.numKeys >= 3) {
      prop0.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 1: logo (opacity) ---
  // no asset — using placeholder solid
  var layer1 = comp.layers.addSolid([0.18, 0.18, 0.18], "logo", comp.width, comp.height, 1.0);
  layer1.name = "logo";
  var tg1 = layer1.property("ADBE Transform Group");
  var prop1 = tg1.property("Opacity");
  prop1.setValueAtTime(0 / comp.frameRate, 0);
  prop1.setValueAtTime(24 / comp.frameRate, 100);
  
  if (prop1.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop1.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop1.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop1.numKeys >= 3) {
      prop1.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  comp.openInViewer();
  alert("Created: logo-reveal\nLayers: 2\nDuration: 0.8s @ 30fps");
})();
