// Generated by animate-pipeline — test-enter
// Run in After Effects: File > Scripts > Run Script File

(function() {
  var comp = app.project.items.addComp(
    "test-enter",
    1294, 720, 1,
    1, 30
  );

  // --- Layer 0: box (translateY) ---
  // no asset — using placeholder solid
  var layer0 = comp.layers.addSolid([0.18, 0.18, 0.18], "box", comp.width, comp.height, 1.0);
  layer0.name = "box";
  var tg0 = layer0.property("ADBE Transform Group");
  var prop0 = tg0.property("Position");
  prop0.setValueAtTime(0 / comp.frameRate, [0, 100]);
  prop0.setValueAtTime(30 / comp.frameRate, [0, 0]);
  if (prop0.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop0.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop0.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop0.numKeys >= 3) {
      prop0.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  comp.openInViewer();
  alert("Created: test-enter\nLayers: 1\nDuration: 1s @ 30fps");
})();
