/**
 * card-fade-slide-up — Three.js scene
 * Generated by the animate pipeline. Edit freely.
 *
 * Install: npm install three gsap
 * Duration: 1.2s  FPS: 30
 */

import * as THREE from 'three';
import { gsap } from 'gsap';

/**
 * @param {HTMLElement} container
 * @returns {{ renderer, scene, camera, tl, play, dispose }}
 */
export function createCardFadeSlideUpScene(container) {
  // ─── Renderer ────────────────────────────────────────────
  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
  renderer.setPixelRatio(window.devicePixelRatio);
  renderer.setSize(container.clientWidth, container.clientHeight);
  container.appendChild(renderer.domElement);

  // ─── Scene ───────────────────────────────────────────────
  const scene = new THREE.Scene();

  // ─── Camera ──────────────────────────────────────────────
  const aspect = container.clientWidth / container.clientHeight;
  const camera = new THREE.PerspectiveCamera(60, aspect, 0.1, 1000);
  camera.position.set(0, 0, 5);

  // ─── Lights ──────────────────────────────────────────────
  scene.add(new THREE.AmbientLight(0xffffff, 0.8));
  const dirLight = new THREE.DirectionalLight(0xffffff, 0.6);
  dirLight.position.set(2, 4, 3);
  scene.add(dirLight);

  // ─── Objects (one mesh per spec layer id) ────────────────
  const cardMesh = new THREE.Mesh(new THREE.BoxGeometry(1.5, 2, 0.05), new THREE.MeshStandardMaterial({ color: 0x888888, transparent: true, opacity: 1 }));
  scene.add(cardMesh);

  // ─── Animation timeline ──────────────────────────────────
  const tl = gsap.timeline({ paused: true });

  tl.from(cardMesh.position, { y: -1.2, duration: 1.2, ease: 'back.out(1.7)' }, 0); // ~spring: stiffness 200, damping 12
  tl.from(cardMesh.material, { opacity: 0, duration: 0.5, ease: 'power2.out' }, 0);

  // ─── Render loop ─────────────────────────────────────────
  let rafId;
  function animate() {
    rafId = requestAnimationFrame(animate);
    renderer.render(scene, camera);
  }
  animate();

  // ─── Resize ──────────────────────────────────────────────
  function onResize() {
    const w = container.clientWidth, h = container.clientHeight;
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
    renderer.setSize(w, h);
  }
  window.addEventListener('resize', onResize);

  return {
    renderer,
    scene,
    camera,
    tl,
    play: () => tl.play(),
    dispose: () => {
      cancelAnimationFrame(rafId);
      window.removeEventListener('resize', onResize);
      renderer.dispose();
      container.removeChild(renderer.domElement);
    },
  };
}
