// src/animations/registry.ts
// AUTO-GENERATED by animate-pipeline — do not edit manually
// Each entry registers one animation composition in Remotion.

import type { ComponentType } from 'react';
import type { AnimationSpec } from './types';

export interface AnimationRegistration {
  id: string;
  component: ComponentType;
  spec: AnimationSpec;
}

export const animationRegistry: AnimationRegistration[] = [
  // __REGISTRY_END__
];
