// Generated by animate-pipeline — payment-methods-carousel
// Run in After Effects: File > Scripts > Run Script File

(function() {
  var comp = app.project.items.addComp(
    "payment-methods-carousel",
    1294, 720, 1,
    4.5, 30
  );

  // --- Layer 0: carousel-rig (rotateY) ---
  // no asset — using placeholder solid
  var layer0 = comp.layers.addSolid([0.18, 0.18, 0.18], "carousel-rig", comp.width, comp.height, 1.0);
  layer0.name = "carousel-rig";
  var tg0 = layer0.property("ADBE Transform Group");
  var prop0 = tg0.property("Y Rotation");
  prop0.setValueAtTime(0 / comp.frameRate, 0);
  prop0.setValueAtTime(135 / comp.frameRate, 360);
  
  if (prop0.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 33);
    var easeIn  = new KeyframeEase(0, 33);
    prop0.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop0.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop0.numKeys >= 3) {
      prop0.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 1: visa-card (scale) ---
  // asset: cards/visa.svg — copy to project, link manually
  var layer1 = comp.layers.addSolid([0.18, 0.18, 0.18], "visa-card", comp.width, comp.height, 1.0);
  layer1.name = "visa-card";
  var tg1 = layer1.property("ADBE Transform Group");
  var prop1 = tg1.property("Scale");
  prop1.setValueAtTime(90 / comp.frameRate, 1.2);
  prop1.setValueAtTime(135 / comp.frameRate, 1);
  
  if (prop1.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop1.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop1.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop1.numKeys >= 3) {
      prop1.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 2: mastercard-card (translateX) ---
  // asset: cards/mastercard.svg — copy to project, link manually
  var layer2 = comp.layers.addSolid([0.18, 0.18, 0.18], "mastercard-card", comp.width, comp.height, 1.0);
  layer2.name = "mastercard-card";
  var tg2 = layer2.property("ADBE Transform Group");
  var prop2 = tg2.property("Position");
  prop2.setValueAtTime(90 / comp.frameRate, [266, 0]);
  prop2.setValueAtTime(135 / comp.frameRate, [160, 0]);
  
  if (prop2.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop2.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop2.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop2.numKeys >= 3) {
      prop2.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 3: mastercard-card (translateY) ---
  // asset: cards/mastercard.svg — copy to project, link manually
  var layer3 = comp.layers.addSolid([0.18, 0.18, 0.18], "mastercard-card", comp.width, comp.height, 1.0);
  layer3.name = "mastercard-card";
  var tg3 = layer3.property("ADBE Transform Group");
  var prop3 = tg3.property("Position");
  prop3.setValueAtTime(90 / comp.frameRate, [0, 0]);
  prop3.setValueAtTime(135 / comp.frameRate, [0, 520]);
  
  if (prop3.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 33);
    var easeIn  = new KeyframeEase(0, 33);
    prop3.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop3.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop3.numKeys >= 3) {
      prop3.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 4: mastercard-card (opacity) ---
  // asset: cards/mastercard.svg — copy to project, link manually
  var layer4 = comp.layers.addSolid([0.18, 0.18, 0.18], "mastercard-card", comp.width, comp.height, 1.0);
  layer4.name = "mastercard-card";
  var tg4 = layer4.property("ADBE Transform Group");
  var prop4 = tg4.property("Opacity");
  prop4.setValueAtTime(90 / comp.frameRate, 100);
  prop4.setValueAtTime(135 / comp.frameRate, 0);
  
  if (prop4.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop4.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop4.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop4.numKeys >= 3) {
      prop4.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 5: applepay-card (translateX) ---
  // asset: cards/apple-pay.svg — copy to project, link manually
  var layer5 = comp.layers.addSolid([0.18, 0.18, 0.18], "applepay-card", comp.width, comp.height, 1.0);
  layer5.name = "applepay-card";
  var tg5 = layer5.property("ADBE Transform Group");
  var prop5 = tg5.property("Position");
  prop5.setValueAtTime(90 / comp.frameRate, [165, 0]);
  prop5.setValueAtTime(135 / comp.frameRate, [320, 0]);
  
  if (prop5.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop5.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop5.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop5.numKeys >= 3) {
      prop5.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 6: applepay-card (translateY) ---
  // asset: cards/apple-pay.svg — copy to project, link manually
  var layer6 = comp.layers.addSolid([0.18, 0.18, 0.18], "applepay-card", comp.width, comp.height, 1.0);
  layer6.name = "applepay-card";
  var tg6 = layer6.property("ADBE Transform Group");
  var prop6 = tg6.property("Position");
  prop6.setValueAtTime(90 / comp.frameRate, [0, 0]);
  prop6.setValueAtTime(135 / comp.frameRate, [0, 520]);
  
  if (prop6.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 33);
    var easeIn  = new KeyframeEase(0, 33);
    prop6.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop6.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop6.numKeys >= 3) {
      prop6.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 7: applepay-card (opacity) ---
  // asset: cards/apple-pay.svg — copy to project, link manually
  var layer7 = comp.layers.addSolid([0.18, 0.18, 0.18], "applepay-card", comp.width, comp.height, 1.0);
  layer7.name = "applepay-card";
  var tg7 = layer7.property("ADBE Transform Group");
  var prop7 = tg7.property("Opacity");
  prop7.setValueAtTime(90 / comp.frameRate, 100);
  prop7.setValueAtTime(135 / comp.frameRate, 0);
  
  if (prop7.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop7.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop7.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop7.numKeys >= 3) {
      prop7.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 8: ach-card (translateX) ---
  // asset: cards/ach.svg — copy to project, link manually
  var layer8 = comp.layers.addSolid([0.18, 0.18, 0.18], "ach-card", comp.width, comp.height, 1.0);
  layer8.name = "ach-card";
  var tg8 = layer8.property("ADBE Transform Group");
  var prop8 = tg8.property("Position");
  prop8.setValueAtTime(90 / comp.frameRate, [-165, 0]);
  prop8.setValueAtTime(135 / comp.frameRate, [-160, 0]);
  
  if (prop8.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop8.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop8.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop8.numKeys >= 3) {
      prop8.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 9: ach-card (translateY) ---
  // asset: cards/ach.svg — copy to project, link manually
  var layer9 = comp.layers.addSolid([0.18, 0.18, 0.18], "ach-card", comp.width, comp.height, 1.0);
  layer9.name = "ach-card";
  var tg9 = layer9.property("ADBE Transform Group");
  var prop9 = tg9.property("Position");
  prop9.setValueAtTime(90 / comp.frameRate, [0, 0]);
  prop9.setValueAtTime(135 / comp.frameRate, [0, 520]);
  
  if (prop9.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 33);
    var easeIn  = new KeyframeEase(0, 33);
    prop9.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop9.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop9.numKeys >= 3) {
      prop9.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 10: ach-card (opacity) ---
  // asset: cards/ach.svg — copy to project, link manually
  var layer10 = comp.layers.addSolid([0.18, 0.18, 0.18], "ach-card", comp.width, comp.height, 1.0);
  layer10.name = "ach-card";
  var tg10 = layer10.property("ADBE Transform Group");
  var prop10 = tg10.property("Opacity");
  prop10.setValueAtTime(90 / comp.frameRate, 100);
  prop10.setValueAtTime(135 / comp.frameRate, 0);
  
  if (prop10.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop10.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop10.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop10.numKeys >= 3) {
      prop10.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 11: wire-card (translateX) ---
  // asset: cards/wire.svg — copy to project, link manually
  var layer11 = comp.layers.addSolid([0.18, 0.18, 0.18], "wire-card", comp.width, comp.height, 1.0);
  layer11.name = "wire-card";
  var tg11 = layer11.property("ADBE Transform Group");
  var prop11 = tg11.property("Position");
  prop11.setValueAtTime(90 / comp.frameRate, [-266, 0]);
  prop11.setValueAtTime(135 / comp.frameRate, [-320, 0]);
  
  if (prop11.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop11.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop11.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop11.numKeys >= 3) {
      prop11.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 12: wire-card (translateY) ---
  // asset: cards/wire.svg — copy to project, link manually
  var layer12 = comp.layers.addSolid([0.18, 0.18, 0.18], "wire-card", comp.width, comp.height, 1.0);
  layer12.name = "wire-card";
  var tg12 = layer12.property("ADBE Transform Group");
  var prop12 = tg12.property("Position");
  prop12.setValueAtTime(90 / comp.frameRate, [0, 0]);
  prop12.setValueAtTime(135 / comp.frameRate, [0, 520]);
  
  if (prop12.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 33);
    var easeIn  = new KeyframeEase(0, 33);
    prop12.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop12.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop12.numKeys >= 3) {
      prop12.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 13: wire-card (opacity) ---
  // asset: cards/wire.svg — copy to project, link manually
  var layer13 = comp.layers.addSolid([0.18, 0.18, 0.18], "wire-card", comp.width, comp.height, 1.0);
  layer13.name = "wire-card";
  var tg13 = layer13.property("ADBE Transform Group");
  var prop13 = tg13.property("Opacity");
  prop13.setValueAtTime(90 / comp.frameRate, 100);
  prop13.setValueAtTime(135 / comp.frameRate, 0);
  
  if (prop13.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop13.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop13.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop13.numKeys >= 3) {
      prop13.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 14: selection-ring (opacity) ---
  // no asset — using placeholder solid
  var layer14 = comp.layers.addSolid([0.18, 0.18, 0.18], "selection-ring", comp.width, comp.height, 1.0);
  layer14.name = "selection-ring";
  var tg14 = layer14.property("ADBE Transform Group");
  var prop14 = tg14.property("Opacity");
  prop14.setValueAtTime(75 / comp.frameRate, 0);
  prop14.setValueAtTime(135 / comp.frameRate, 100);
  
  if (prop14.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 10);
    var easeIn  = new KeyframeEase(0, 60);
    prop14.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop14.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop14.numKeys >= 3) {
      prop14.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  // --- Layer 15: selection-ring (scale) ---
  // no asset — using placeholder solid
  var layer15 = comp.layers.addSolid([0.18, 0.18, 0.18], "selection-ring", comp.width, comp.height, 1.0);
  layer15.name = "selection-ring";
  var tg15 = layer15.property("ADBE Transform Group");
  var prop15 = tg15.property("Scale");
  prop15.setValueAtTime(75 / comp.frameRate, 1.35);
  prop15.setValueAtTime(135 / comp.frameRate, 1.05);
  
  if (prop15.numKeys >= 2) {
    var easeOut = new KeyframeEase(0, 40);
    var easeIn  = new KeyframeEase(0, 20);
    prop15.setTemporalEaseAtKey(1, [easeOut], [easeIn]);
    prop15.setTemporalEaseAtKey(2, [easeOut], [easeIn]);
    if (prop15.numKeys >= 3) {
      prop15.setTemporalEaseAtKey(3, [easeOut], [easeIn]);
    }
  }

  comp.openInViewer();
  alert("Created: payment-methods-carousel\nLayers: 16\nDuration: 4.5s @ 30fps");
})();
