import { motion } from 'motion/react';

/**
 * card-fade-slide-up
 * Generated by the animate pipeline. Edit freely.
 *
 * Duration: 1.2s  FPS: 30
 * Install: npm install motion
 */
export function CardFadeSlideUp() {
  return (
    <div
      className="animation-root"
      style={{ width: 800, height: 600, position: 'relative' }}
    >
      <motion.div
        className="card"
        initial={{"y":120,"opacity":0}}
        animate={{"y":0,"opacity":1}}
        transition={{
        "y": {
          "type": "spring",
          "stiffness": 200,
          "damping": 12,
          "mass": 1
        },
        "opacity": {
          "type": "tween",
          "ease": [
            0,
            0,
            0.2,
            1
          ],
          "duration": 0.5
        }
      }}
      />
    </div>
  );
}
